import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";

import Providers from "./providers";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import Image from "next/image";
import nounSwap from "../../public/noun-swap.png";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

function Header() {
    return (
        <header className="flex flex-row justify-between h-12 items-center w-full ">
            <Link href="/">
                <Image src={nounSwap} alt="Noun Swap" height={30} />
            </Link>
            <ConnectButton />
        </header>
    );
}

function Footer() {
    return <footer className="pt-10">Paperclip Labs</footer>;
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <div className={inter.className + " flex flex-col min-h-screen justify-between p-6 bg-gray-100 "}>
                        <Header />
                        <main className="flex flex-col grow self-start justify-start py-12 ">{children}</main>
                        <Footer />
                    </div>
                </Providers>
            </body>
        </html>
    );
}
